
#===-------------------------------------------------------------------------------------------===//
# llvm-gitlab-runner-service - The image used to run gitlab-runner workers
#===-------------------------------------------------------------------------------------------===//
FROM ericwf/builder-base:latest AS llvm-gitlab-runner-service

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    bash-completion \
    vim \
    sudo \
    apt-utils \
  && rm -rf /var/lib/apt/lists/*

ENV GITLAB_CONFIG_VOLUME=/srv/llvm-gitlab-runner-config
ENV GITLAB_TOOLS=/gitlab-tools

# Install Docker (used by gitlab runner)
ADD scripts/install_docker.sh /tmp/install_docker.sh
RUN /tmp/install_docker.sh && rm /tmp/install_docker.sh


# Install gitlab runner
ADD scripts/install_gitlab_runner.sh /tmp/install_gitlab_runner.sh
RUN /tmp/install_gitlab_runner.sh && rm /tmp/install_gitlab_runner.sh

ADD scripts/register_and_run_gitlab_runner.sh $GITLAB_TOOLS/

ENTRYPOINT $GITLAB_TOOLS/register_and_run_gitlab_runner.sh "$@"
