
#===-------------------------------------------------------------------------------------------===//
# llvm-gitlab-runner-service - The image used to run gitlab-runner workers
#===-------------------------------------------------------------------------------------------===//
FROM ericwf/builder-base:latest AS llvm-gitlab-runner-service

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    bash-completion \
    vim \
    sudo \
    apt-utils \
  && rm -rf /var/lib/apt/lists/*

ENV GITLAB_CONFIG_VOLUME=/srv/llvm-gitlab-runner-config
ENV GITLAB_SCRIPTS=/llvm-gitlab-scripts


# Install Docker (used by gitlab runner)
ADD scripts/install_docker.sh /tmp/install_docker.sh
RUN /tmp/install_docker.sh && rm /tmp/install_docker.sh

RUN curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64 \
  &&  chmod +x /usr/local/bin/gitlab-runner \
  && useradd --comment 'LLVM GitLab Runner' --create-home gitlab-runner --shell /bin/bash


# Install gcloud SDK
ADD scripts/install_cloud_sdk.sh /tmp/
RUN /tmp/install_cloud_sdk.sh && rm /tmp/install_cloud_sdk.sh

ADD config/ /etc/gitlab-runner

RUN gitlab-runner register \
  --non-interactive \
  --executor "docker+machine" \
  --docker-image ericwf/llvm-gitlab-runner-worker:latest \
  --url "https://gitlab.com/" \
  --registration-token "$TOKEN" \
  --description "llvm-docker-runner" \
  --tag-list "docker,google-cloud" \
  --run-untagged="true" \
  --locked="false" \
  --access-level="not_protected"


CMD $GITLAB_SCRIPTS/register_and_run_gitlab_runner.sh "$@"
